export const stopWords = new Set<string>([
  "the", "and", "for", "you", "your", "this", "that", "with", "have", "has", "was", "were",
  "are", "but", "not", "can", "could", "would", "should", "will", "just", "like", "what",
  "when", "how", "why", "who", "which", "from", "into", "about", "more", "most", "some",
  "any", "all", "out", "get", "got", "one", "two", "its", "his", "her", "their", "them",
  "they", "there", "here", "then", "than", "very", "much", "really", "please", "thanks",
  "thank", "video", "videos", "channel", "watch", "watching", "watched", "make", "made",
  "making", "want", "wanted", "need", "needs", "see", "seen", "look", "looks", "good",
  "great", "nice", "love", "loved", "best", "also", "still", "even", "back", "over",
  "after", "before", "next", "last", "first", "new", "old", "does", "did", "doing",
  "was", "been", "being", "were", "our", "ours", "yours", "mine", "him", "she", "he",
  "where", "whose", "whom", "whether", "anyone", "everyone", "nobody",
  "right", "sure", "well", "okay", "true", "false", "real", "actual",
  "good", "bad", "big", "small", "long", "short", "hard", "easy", "fast",
  "slow", "high", "low", "full", "free", "open", "close", "next", "last",
  "use", "uses", "using", "used", "work", "works", "working", "worked",
  "take", "takes", "taking", "give", "gives", "giving", "come", "comes",
  "coming", "look", "looking", "looked", "try", "tries", "trying", "tried",
  "run", "runs", "running", "start", "starts", "starting", "stop", "stops",
  "add", "adds", "adding", "set", "sets", "setting", "find", "finds",
  "finding", "help", "helps", "helping", "call", "calls", "called",
  "let", "lets", "put", "puts", "seem", "seems", "feel", "feels",
  "because", "while", "since", "though", "although", "however", "actually",
  "basically", "honestly", "literally", "definitely", "probably", "obviously",
  "simply", "totally", "completely", "seriously", "exactly", "certainly",
  "always", "never", "often", "sometimes", "already", "instead", "rather",
  "enough", "quite", "pretty", "fairly", "almost", "nearly", "around",
  "every", "each", "both", "other", "another", "same", "such", "only",
  "whole", "many", "few", "less", "least", "better", "worse", "worst",
  "thing", "things", "stuff", "way", "ways", "time", "times", "people",
  "guys", "guy", "bro", "man", "dude", "lol", "haha", "wow", "yeah",
  "gonna", "wanna", "kinda", "sorta", "gotta", "cant", "dont", "doesnt",
  "isnt", "wasnt", "arent", "wont", "wouldnt", "couldnt", "shouldnt",
  "show", "tell", "explain", "cover", "teach", "tutorial", "walkthrough",
  "guide", "demo", "part", "wondering", "curious", "question", "asking",
  "asked", "wait", "waiting", "upload", "post", "share", "keep", "going",
  "something", "anything", "everything", "someone", "maybe", "think",
  "it", "is", "in", "on", "of", "to", "a", "an", "as", "at", "by", "be", "or", "if",
  "so", "do", "no", "yes", "up", "we", "me", "my", "i", "u", "ur", "pls", "plz"
]);
